import{a as y,S as g,i as c}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function a(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=a(t);fetch(t.href,r)}})();const b="44774243-c5238725a8321193973133c91";y.defaults.baseURL="https://pixabay.com/api/";async function w(e,o=1,a=15){try{return(await y.get("",{params:{key:b,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:a}})).data}catch(s){throw new Error(s.message)}}function L(e){const o=document.querySelector(".gallery"),a=e.map(({webformatURL:s,largeImageURL:t,tags:r,likes:i,views:m,comments:p,downloads:h})=>`<div class="photo-card">
          <a href="${t}">
            <img src="${s}" alt="${r}" loading="lazy" />
          </a>
          <div class="info">
            <p class="info-item"><b>Likes</b> ${i}</p>
            <p class="info-item"><b>Views</b> ${m}</p>
            <p class="info-item"><b>Comments</b> ${p}</p>
            <p class="info-item"><b>Downloads</b> ${h}</p>
          </div>
        </div>`).join("");o.innerHTML+=a,new g(".photo-card a",{captionsData:"alt",captionDelay:250}).refresh()}const S=document.querySelector(".search-form"),v=document.querySelector(".gallery"),u=document.querySelector(".loader"),n=document.createElement("button");n.textContent="Load more";n.style.display="none";document.body.appendChild(n);let d="",l=1;S.addEventListener("submit",q);n.addEventListener("click",E);async function q(e){if(e.preventDefault(),d=e.currentTarget.elements.searchQuery.value.toLowerCase(),d===""){c.error({title:"Error",message:"Please enter a search query!"});return}l=1,v.innerHTML="",n.style.display="none",await f()}async function E(){l+=1,await f(),$()}async function f(){u.style.display="block";try{const e=await w(d,l);e.hits.length===0?c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(L(e.hits),n.style.display=e.hits.length<e.totalHits?"block":"none",e.totalHits<=l*15&&(c.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}),n.style.display="none"))}catch(e){c.error({title:"Error",message:`Something went wrong: ${e.message}`})}finally{u.style.display="none"}}function $(){const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
